# Generated by Django 5.2.6 on 2025-09-16 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration', models.CharField(blank=True, max_length=50)),
                ('branch', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('passing_year_10', models.CharField(blank=True, max_length=4)),
                ('percentage_10', models.CharField(blank=True, max_length=10)),
                ('education', models.CharField(blank=True, max_length=20)),
                ('passing_year_12', models.CharField(blank=True, max_length=4)),
                ('percentage_12', models.CharField(blank=True, max_length=10)),
                ('passing_year_diploma', models.CharField(blank=True, max_length=4)),
                ('percentage_diploma', models.CharField(blank=True, max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
