# Generated by Django 4.2.11 on 2026-03-29 08:06

from django.db import migrations, models
import django.db.models.deletion


def clear_old_questions(apps, schema_editor):
    """Clear old Question rows that have no valid Subject FK."""
    Question = apps.get_model('accounts', 'Question')
    Question.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_subject_testresult'),
    ]

    operations = [
        migrations.RunPython(clear_old_questions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='question',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='question',
            name='test_type',
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='accounts.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('company', 'Company'), ('aptitude', 'Aptitude')], default='technical', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='icon',
            field=models.CharField(default='📚', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testresult',
            name='violations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=500),
        ),
    ]
