# Generated by Django 4.2.11 on 2026-03-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_question_test_name_remove_question_test_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='auto_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='tab_switches',
            field=models.IntegerField(default=0),
        ),
    ]
