# Generated by Django 4.2.11 on 2026-03-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_testresult_auto_submitted_testresult_tab_switches'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
