# Generated by Django 4.2.11 on 2026-03-31 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='My Resume', max_length=200)),
                ('style_choice', models.CharField(choices=[('modernist', 'The Modernist'), ('executive', 'The Executive'), ('creative', 'The Creative')], default='modernist', max_length=20)),
                ('resume_json_text', models.TextField(blank=True, default='{}')),
                ('brand_color', models.CharField(default='#6366f1', max_length=7)),
                ('ats_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
