# Generated by Django 5.2.6 on 2026-04-01 06:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='face_violations',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ProctoringViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('tab_switch', 'Tab Switch'), ('multi_face', 'Multiple Faces')], max_length=20)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_violations', to='mock_interview.interviewsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
