# Generated by Django 4.2.11 on 2026-04-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0003_interviewsession_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionresponse',
            name='improvements',
        ),
        migrations.RemoveField(
            model_name='questionresponse',
            name='strengths',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='improvements_text',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='strengths_text',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
